### ISSUE TITLE
Generate a flow direction map

### ISSUE THREAD

**Issue by liufeng0612** [mllam/neural-lam#14]
![dem格网](https://github.com/joeloskarsson/neural-lam/assets/49362589/85b24f9d-8fbd-40bc-b009-65cde1988336)
![图片2](https://github.com/joeloskarsson/neural-lam/assets/49362589/daae4ef4-97dc-4118-a236-be82b0b7b6a2)
Dear Mr. Joel Oskarsson, in the 'Graph Construction' section of your paper, you aggregate neighbor nodes in eight directions. A student would like to ask for your advice on how to selectively aggregate neighbor nodes. Could you also explain how to generate a flow direction map, for example, as shown below: Based on neighbors in the D8 or D4 directions, generate a flow direction map from the DEM image, and then aggregate the neighbor features of upstream river nodes. Article source: https://eartharxiv.org/repository/view/3018/, but this article does not share its code, which is very challenging for beginners.

**Comment by sadamov** [comment]
I am closing this issue because it has become stale.
