### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leifdenby** [mllam/neural-lam#36]
I am just creating an issue so that I can create a link to the roadmap document on google docs: https://docs.google.com/document/d/1csgMjyuE1Up2m262e-N7qMPmNJ-zHLguGyrgvnjTuBE/edit.

I will pin this to the top of the issues list

(We can close this issue if people would prefer to see this elsewhere)

**Comment by joeloskarsson** [comment]
I was thinking about this with having too many different tools and platforms related to neural-lam. One idea could be to try to move the roadmap to a wiki page in the repository. Then it's directly in the same place as the code. But I can't for the love of me figure out how to activate the wiki tab to even test that out :confused: .

I also read a bit about [github project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects), which is in some ways tailored exactly for keeping track of roadmaps. But I think that functionality is overkill for what we need here.

**Comment by sadamov** [comment]
Here you go: https://github.com/mllam/neural-lam/wiki/Roadmap

**Comment by joeloskarsson** [comment]
Great! I think that looks nice and convenient. Any input on moving the roadmap to the wiki @leifdenby ? If we are happy with it we can close this and add a note in the readme pointing to the wiki page.

**Comment by leifdenby** [comment]
Wow! I love the roadmap wiki. Amazing work @sadamov! It is a little harder to move things around on the wiki since we can edit in real-time together, but I am happy to try with the wiki instead if you guys would prefer that. Github does also have a sort of "trello board" thing, but maybe we go with the wiki for now.

Should I add a comment to the top of the roadmap google doc to say it is deprecated and people should look at the wiki instead? (and link to it)

**Comment by joeloskarsson** [comment]
If you are happy with it then I think you can do that Leif. Two things to keep in mind though (maybe before deprecating the google doc?):

- Who has the rights to edit the wiki? Who do we want to have rights to do this? (In the same way I could not find the settings to enable the wiki I can not find any settings about the wiki permissions either :sweat_smile: ).
  - To me it seems enough for now if us as repository admins can edit it
- It would be good to have some form of routine for how to update the roadmap. I for one have some things I think could be on there, but I don't want to just write it there without discussing it over with someone else. I don't know what's the easiest solution. 
  - Perhaps it is enough to have a meeting the three of us (+ anyone else who wants to join) and prioritize for the next couple of milestones. 
  - Another option is that we just let everything start at issues and in those issues decide to place them in the roadmap if it feels important enough.

**Comment by sadamov** [comment]
you can change the settings here Joel at the bottom
![image](https://github.com/mllam/neural-lam/assets/45732287/ffc54db2-5e8f-42cb-b5cc-5a8c2fba2a5a)

**Comment by joeloskarsson** [comment]
Oooh I see!! Thanks a lot. I was looking frenetically in the menu to the left for the "Features" page :facepalm: 

I disabled discussions now, since we are not using that feature. Better to just have as issues atm.

**Comment by joeloskarsson** [comment]
Closing this as 

1. We seem happy to keep the roadmap in the wiki.
2. The roadmap will be updated on regular developer calls.
