### ISSUE TITLE
Asking new contributors to assign reviewers, which is not possible

### ISSUE THREAD

**Issue by joeloskarsson** [mllam/neural-lam#73]
When setting up #72 @ErikLarssonDev noticed that as a new contributor you can not actually assign reviewers and asignees to PRs. But we request this in the PR template:

https://github.com/mllam/neural-lam/blob/4969f92ad974f136089d15e7e2e2e9d73a43590d/.github/pull_request_template.md?plain=1#L29

Reading https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review it indeed seems to be the case that only users with write access to the repo can actually assign reviewers to their PR.

What we now have in the PR template then seems contradictory, and we probably don't want to keep giving write access to anyone who want to contribute. Should we just clarify the PR template that this only applies if you can, or what's your thoughts @leifdenby @sadamov ?

**Comment by sadamov** [comment]
True. I agree to change the template and add smth like "if you have at least write-access". The admins should then make sure to receive notifcations about new PRs, otherwise they might be unnoticed.
![image](https://github.com/user-attachments/assets/03d0f28c-d608-4270-b0ab-9ec05645a23e)
